language: node_js
node_js:
- "stable"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- C:/Users/navra/OneDrive/Desktop/newmanReports run tests/StarWarApiTest.json